# Generated by Django 4.0.4 on 2022-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('deadline', models.DateTimeField()),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('ammount', models.IntegerField()),
            ],
        ),
    ]
