# Generated by Django 4.0.4 on 2022-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
