# Generated by Django 4.0.4 on 2022-05-25 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
